#!/bin/bash
set -e

mkdir -p assets
export CGO_ENABLED=1

godep go build -o assets/smuggler ./cmd/smuggler

for GOOS in darwin linux; do
  for GOARCH in 386 amd64; do
    echo "Building $GOOS-$GOARCH"
    export GOOS=$GOOS
    export GOARCH=$GOARCH
	godep go build -o assets/smuggler-$GOOS-$GOARCH ./cmd/smuggler
  done
done

