#!/bin/bash
set -e

SMUGGLER_DOCKER_TAG=${SMUGGLER_DOCKER_TAG:-redfactorlabs/concourse-smuggler-resource:ubuntu-14.04}

go install github.com/tools/godep
godep restore
./scripts/test
./scripts/build
docker build -t ${SMUGGLER_DOCKER_TAG} .
docker push ${SMUGGLER_DOCKER_TAG}
