#!/bin/bash
set -eu
SMUGGLER_DOCKER_TAG="${SMUGGLER_DOCKER_TAG:-ubuntu-14.04}"
SMUGGLER_DOCKER_REPOSITORY="${SMUGGLER_DOCKER_REPOSITORY:-redfactorlabs/concourse-smuggler-resource}"
SMUGGLER_DOCKER_IMAGE="${SMUGGLER_DOCKER_REPOSITORY}:${SMUGGLER_DOCKER_TAG}"

if ! which go > /dev/null; then
  echo "You need GO binary to run this script."
  exit 1
fi

if ! which godep > /dev/null; then
  echo "Installing godep..."
  go get github.com/tools/godep
fi

echo "Restoring dependencies..."
godep restore
./scripts/test
./scripts/build

docker build -t "${SMUGGLER_DOCKER_IMAGE}" .
docker push "${SMUGGLER_DOCKER_IMAGE}"
